"""
SAFEBAND AI - Demonstration Scenario Profiles

Deterministic sensor profiles used for development, testing,
demonstrations, and validation of the SAFEBAND AI pipeline.

IMPORTANT
---------
These profiles are DATA SOURCES only.

They are NOT user-controlled activity classifications.

The activity-recognition layer should infer activity from the
sensor values generated by these profiles.

Available profiles:
    NORMAL
    WALKING
    RUNNING
    FALL
    HIGH_RISK
    SOS

Sensor mapping:

    MAX30102
        heart_rate
        spo2

    MAX30208
        body_temperature

    BNO055
        acceleration_x
        acceleration_y
        acceleration_z
        motion_intensity
        orientation

    BME680
        temperature
        humidity
        pressure

    INMP441
        audio_level

    GPS
        latitude
        longitude
"""


from typing import Any, Dict, List


# ============================================================
# NORMAL
# ============================================================

NORMAL_SCENARIO: Dict[str, Any] = {
    "scenario": "NORMAL",

    "description": (
        "User is stationary and monitored parameters "
        "are within normal ranges."
    ),

    # --------------------------------------------------------
    # MAX30102 - Physiological
    # --------------------------------------------------------

    "heart_rate": 74.0,
    "spo2": 98.0,

    # --------------------------------------------------------
    # MAX30208 - Body Temperature
    # --------------------------------------------------------

    "body_temperature": 36.6,

    # --------------------------------------------------------
    # BNO055 - Motion
    # --------------------------------------------------------

    "acceleration_x": 0.02,
    "acceleration_y": 0.01,
    "acceleration_z": 1.00,

    "motion_intensity": 0.08,
    "orientation": 5.0,

    # --------------------------------------------------------
    # BME680 - Environment
    # --------------------------------------------------------

    "temperature": 27.0,
    "humidity": 58.0,
    "pressure": 1012.0,

    # --------------------------------------------------------
    # INMP441 - Audio
    # --------------------------------------------------------

    "audio_level": 0.08,

    # --------------------------------------------------------
    # GPS
    # --------------------------------------------------------

    "latitude": 19.0760,
    "longitude": 72.8777,

    # --------------------------------------------------------
    # Emergency Input
    # --------------------------------------------------------

    "manual_sos": False,
}


# ============================================================
# WALKING
# ============================================================

WALKING_SCENARIO: Dict[str, Any] = {
    "scenario": "WALKING",

    "description": (
        "Sensor pattern representing normal walking activity."
    ),

    # MAX30102
    "heart_rate": 86.0,
    "spo2": 98.0,

    # MAX30208
    "body_temperature": 36.8,

    # BNO055
    "acceleration_x": 0.18,
    "acceleration_y": 0.12,
    "acceleration_z": 1.12,

    "motion_intensity": 0.45,
    "orientation": 8.0,

    # BME680
    "temperature": 27.2,
    "humidity": 57.0,
    "pressure": 1012.0,

    # INMP441
    "audio_level": 0.12,

    # GPS
    "latitude": 19.0764,
    "longitude": 72.8781,

    # Emergency Input
    "manual_sos": False,
}


# ============================================================
# RUNNING
# ============================================================

RUNNING_SCENARIO: Dict[str, Any] = {
    "scenario": "RUNNING",

    "description": (
        "Sensor pattern representing high-intensity "
        "running activity."
    ),

    # MAX30102
    "heart_rate": 118.0,
    "spo2": 96.0,

    # MAX30208
    "body_temperature": 37.1,

    # BNO055
    "acceleration_x": 0.85,
    "acceleration_y": 0.65,
    "acceleration_z": 1.35,

    "motion_intensity": 1.55,
    "orientation": 15.0,

    # BME680
    "temperature": 28.5,
    "humidity": 55.0,
    "pressure": 1011.0,

    # INMP441
    "audio_level": 0.30,

    # GPS
    "latitude": 19.0770,
    "longitude": 72.8788,

    # Emergency Input
    "manual_sos": False,
}


# ============================================================
# FALL
# ============================================================

FALL_SCENARIO: Dict[str, Any] = {
    "scenario": "FALL",

    "description": (
        "Sensor pattern containing sudden abnormal motion "
        "and orientation consistent with a possible fall."
    ),

    # MAX30102
    "heart_rate": 112.0,
    "spo2": 96.0,

    # MAX30208
    "body_temperature": 36.9,

    # BNO055
    #
    # Strong acceleration + high motion + abnormal orientation
    # provide the primary fall-detection signature.
    #
    "acceleration_x": 1.80,
    "acceleration_y": 1.40,
    "acceleration_z": 2.00,

    "motion_intensity": 2.80,
    "orientation": 82.0,

    # BME680
    "temperature": 27.4,
    "humidity": 59.0,
    "pressure": 1012.0,

    # INMP441
    "audio_level": 0.72,

    # GPS
    "latitude": 19.0775,
    "longitude": 72.8792,

    # Emergency Input
    "manual_sos": False,
}


# ============================================================
# HIGH RISK
# ============================================================

HIGH_RISK_SCENARIO: Dict[str, Any] = {
    "scenario": "HIGH_RISK",

    "description": (
        "Multiple sensor parameters indicate an abnormal "
        "condition requiring increased monitoring."
    ),

    # MAX30102
    "heart_rate": 128.0,
    "spo2": 92.0,

    # MAX30208
    #
    # Body temperature is intentionally separate from the
    # environmental temperature below.
    #
    "body_temperature": 38.4,

    # BNO055
    "acceleration_x": 0.90,
    "acceleration_y": 0.70,
    "acceleration_z": 1.40,

    "motion_intensity": 1.75,
    "orientation": 68.0,

    # BME680
    "temperature": 39.5,
    "humidity": 72.0,
    "pressure": 1008.0,

    # INMP441
    "audio_level": 0.65,

    # GPS
    "latitude": 19.0778,
    "longitude": 72.8795,

    # Emergency Input
    "manual_sos": False,
}


# ============================================================
# SOS
# ============================================================

SOS_SCENARIO: Dict[str, Any] = {
    "scenario": "SOS",

    "description": (
        "Manual emergency SOS activated by the user."
    ),

    # MAX30102
    "heart_rate": 105.0,
    "spo2": 97.0,

    # MAX30208
    "body_temperature": 36.9,

    # BNO055
    "acceleration_x": 0.10,
    "acceleration_y": 0.08,
    "acceleration_z": 1.02,

    "motion_intensity": 0.15,
    "orientation": 10.0,

    # BME680
    "temperature": 27.5,
    "humidity": 58.0,
    "pressure": 1012.0,

    # INMP441
    "audio_level": 0.10,

    # GPS
    "latitude": 19.0782,
    "longitude": 72.8800,

    # Explicit manual emergency action.
    "manual_sos": True,
}


# ============================================================
# SCENARIO COLLECTION
# ============================================================

SCENARIOS: Dict[str, Dict[str, Any]] = {
    "NORMAL": NORMAL_SCENARIO,
    "WALKING": WALKING_SCENARIO,
    "RUNNING": RUNNING_SCENARIO,
    "FALL": FALL_SCENARIO,
    "HIGH_RISK": HIGH_RISK_SCENARIO,
    "SOS": SOS_SCENARIO,
}


# ============================================================
# PUBLIC FUNCTIONS
# ============================================================

def get_scenario(
    name: str,
) -> Dict[str, Any]:
    """
    Return an independent copy of a demonstration profile.

    Parameters
    ----------
    name:
        Profile name.

    Returns
    -------
    dict
        Independent copy of the requested profile.

    Raises
    ------
    ValueError
        If the requested profile does not exist.
    """

    profile_name = (
        str(name)
        .strip()
        .upper()
    )

    if profile_name not in SCENARIOS:

        available = ", ".join(
            SCENARIOS.keys()
        )

        raise ValueError(
            f"Unknown demonstration profile "
            f"'{name}'. Available profiles: {available}"
        )

    return SCENARIOS[
        profile_name
    ].copy()


def get_available_scenarios() -> List[str]:
    """
    Return all available demonstration profiles.

    Retained for backwards compatibility.
    """

    return list(
        SCENARIOS.keys()
    )


def get_available_profiles() -> List[str]:
    """
    Return all available deterministic sensor profiles.

    Preferred name for the simulation engine.
    """

    return list(
        SCENARIOS.keys()
    )


def is_sos_scenario(
    sensor_data: Dict[str, Any],
) -> bool:
    """
    Determine whether sensor data contains an explicit
    manual SOS request.
    """

    if not isinstance(
        sensor_data,
        dict,
    ):
        return False

    return bool(
        sensor_data.get(
            "manual_sos",
            False,
        )
    )


def get_scenario_description(
    name: str,
) -> str:
    """Return the description of a demonstration profile."""

    scenario = get_scenario(
        name
    )

    return str(
        scenario.get(
            "description",
            "No description available.",
        )
    )


def validate_scenario(
    sensor_data: Dict[str, Any],
) -> bool:
    """
    Validate the core sensor fields contained in a profile.

    This checks data structure only. It does not attempt to
    determine whether the values themselves are medically or
    physically valid.
    """

    if not isinstance(
        sensor_data,
        dict,
    ):
        return False

    required_fields = {
        # MAX30102
        "heart_rate",
        "spo2",

        # MAX30208
        "body_temperature",

        # BNO055
        "acceleration_x",
        "acceleration_y",
        "acceleration_z",
        "motion_intensity",
        "orientation",

        # BME680
        "temperature",
        "humidity",
        "pressure",

        # INMP441
        "audio_level",

        # GPS
        "latitude",
        "longitude",
    }

    return required_fields.issubset(
        sensor_data.keys()
    )


# ============================================================
# PROFILE HELPERS
# ============================================================

def get_profile(
    name: str,
) -> Dict[str, Any]:
    """
    Alias for get_scenario().

    Useful when the application refers to these as
    simulation profiles rather than scenarios.
    """

    return get_scenario(
        name
    )


def is_valid_profile(
    name: str,
) -> bool:
    """Return True if a simulation profile exists."""

    profile_name = (
        str(name)
        .strip()
        .upper()
    )

    return profile_name in SCENARIOS


# ============================================================
# MODULE EXPORTS
# ============================================================

__all__ = [
    # Profiles
    "NORMAL_SCENARIO",
    "WALKING_SCENARIO",
    "RUNNING_SCENARIO",
    "FALL_SCENARIO",
    "HIGH_RISK_SCENARIO",
    "SOS_SCENARIO",
    "SCENARIOS",

    # Retrieval
    "get_scenario",
    "get_profile",

    # Lists
    "get_available_scenarios",
    "get_available_profiles",

    # Validation / detection
    "is_sos_scenario",
    "validate_scenario",
    "is_valid_profile",

    # Description
    "get_scenario_description",
]